### PR TITLE
Update Gruntfile.js

### PR DESCRIPTION
**Pull request by progitter**
fix for issue #86 and #102 . Modified the grunt task to copy over the requires into the dist folder.

### CODE REVIEW

**Comment by dsmorse** [comment]
Looks like all the unit test failed

**Comment by progitter** [comment]
@dsmorse can you checkout why the tests fail? the only change from me was on the gruntfile. That should not have any effect on the unit tests right?

**Comment by progitter** [comment]
@dsmorse looks like the 14 tests that are failing in this PR are currently failing on master.

**Comment by fixmycode** [comment]
@progitter I submitted #118 to fix the tests so once is merged your PR can be merged too.

**Pull request merged**
