### PR TITLE
Rails gem

### PR DESCRIPTION
**Pull request by ened**
**DO NOT MERGE YET**

Beginning of Rails gem.
To test, start a rails app and add this to your Gemfile:
```
gem 'gridster-rails', path: '/path/to/repository'
```
Then, in application.js:
```
//= require jquery.gridster
```
& application.css:
```
 *= require jquery.gridster
```

@dsmorse some questions:
* Do we really need to upload the generated files into this repository? Rails needs those files as well, but they must live in `vendor/assets/`
* The version for the the plugin will always be maintained in the bower.json file, right?

### CODE REVIEW

**Comment by ened** [comment]
Question is whether we could generate the files on dist/vendor only when really needed (e.g. bower / ruby gems upload for distribution), and then delete them afterwards, so they won't clutter the repo.

**Comment by dsmorse** [comment]
We upload the generated files back to the repo, for bower, so my guess is that it would not be needed for the gem.
Yes the version in the bower.json gets bumped every release, so it will be accurate.

**Comment by ened** [comment]
@dsmorse In the meantime, could you create a username/account here: https://rubygems.org/users/new ? (as you are the release manager, I believe you should upload the gem).

**Comment by dsmorse** [comment]
ruby account create: https://rubygems.org/profiles/dsmorse I checked out your code and tested it, I can see the obvious parts that grunt are doing are working, regarding the copies and file modifications, I'm not sure if there is a grunt plugin that will make the gem and publish it.  if not I will need steps, as I'm not a ruby dev.

**Comment by ened** [comment]
This one should work, for the first time, please manually run `gem push gridster-rails-0.6.8.gem` after you run `grunt default shell:build-rails-gem`.

Then `gem` should ask you for your username/password on rubygems.org.

**Comment by dsmorse** [comment]
Looks like when you squashed your commits we lost the copy:rails task, so it fails to build

**Comment by dsmorse** [comment]
Pull request has been merged and we are now publishing to:
 https://rubygems.org/gems/gridster.js-rails

**Pull request closed without merging**
